### ISSUE TITLE
How to run the project in the docker

### ISSUE THREAD

**Issue by bill4u** [Robotics-BUT/Atlas-Fusion#3]
I have create the docker container by the three lines on the very bottom of the dockefile and successfully get the termal with name of "default_user". But where is the source code ? How to run the entire project?
Any help is appreciate. THX!!

**Comment by adamek727** [comment]
Hi, thanks for your interest. The docker does not clone repository on its own. It only makes environment with all dependencies installed in it. To use the code, you have to clone is after running the docker container.
If you have any more questions, do not hesitate to let me know.
